---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# meteorodata

<!-- badges: start -->
<!-- badges: end -->

El objetivo del paquete 'meteorodata' es facilitar el análisis de datos meteorológicos y la manipulación de los mismos mediante funciones implementadas en este paquete.

## Instalación

You can install the development version of meteorodata from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("MatiFasolato/meteorodata")
```

## Ejemplo

Este es un ejemplo básico que muestra cómo instalar la librería del paquete:

```{r example}
library(meteorodata)
F_to_C(100)

estacion_met <- descargar_datos("NH0098", "data_raw/NH0098.csv")
head(estacion_met,5)

C_to_F(23)

grafico <- grafico_temperatura_mensual(
  read.csv("data_raw/NH0098.csv"),
  colores = c("blue", "yellow"),
  titulo = "Promedio Mensual de Temperatura para NH0098"
)
grafico
```

