---
title: "Estaciones-Meteorologicas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Estaciones-Meteorológicas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(meteorodata)
library(dplyr)
library(lubridate)
```


Esta viñeta de prueba nos permite mostrar como funciona la función `F_to_C()`:

```{r}
F_to_C(100)
# descargar_datos("NH0098", "data_raw/NH0098.csv")
```

Esta viñeta de prueba nos permite mostrar como funciona la función `C_to_F()`:
```{r}
C_to_F(23)
```

Esta viñeta de prueba nos permite mostrar como funciona la función `grafico_temp_mensual`:
```{r}
# grafico <- grafico_temperatura_mensual(
#  read.csv("data_raw/NH0098.csv"),
#  colores = c("blue", "yellow"),
#  titulo = "Promedio Mensual de Temperatura para NH0098"
#)
#grafico
```

Esta viñeta de prueba nos permite mostrar como funciona la función `tabla_resumen`:
```{r}
tabla_resumen_temperatura(NH_unidos,c('NH0910','NH0437'))
```

